<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API access token' => '',
    'Email' => '',
    'Expire At' => 'Hết hạn lúc',
    'Not Active' => '',
    'Password' => 'Mật khẩu',
    'Roles' => 'Vai trò',
    'Token' => '',
    '"{attribute}" must be a valid JSON' => '"{attribute}" phải đúng định dạng JSON',
    'Active' => 'Kíck hoạt',
    'Article ID' => 'ID Bài viết',
    'Article View' => 'Xem bài viết',
    'Author' => 'Tác giả',
    'Base URL' => 'Base URL',
    'Base Url' => 'Base Url',
    'Body' => 'Nội dung',
    'Body in english' => 'Nội dung bằng tiếng Anh',
    'Title in english' => 'Tiêu đề bằng tiếng Anh',
    'Caption' => 'Tiêu đề',
    'Carousel ID' => 'ID Carousel',
    'Category' => 'Danh mục',
    'Comment' => 'Bình luận',
    'Component' => 'Thành phần',
    'Config' => 'Cấu hình',
    'Created At' => 'Đã tạo lúc',
    'Created at' => 'Đã tạo lúc',
    'Deleted' => 'Đã xóa',
    'Down to maintenance.' => 'Website đang được nâng cấp, vui lòng quay lại sau, xin cảm ơn!',
    'E-mail' => 'E-mail',
    'File Type' => 'Loại file',
    'Firstname' => 'Tên chính',
    'Gender' => 'Nam',
    'ID' => 'ID',
    'Image' => 'Ảnh',
    'Key' => 'Khóa',
    'Last login' => 'Lần đăng nhập cuối',
    'Lastname' => 'Tên họ',
    'Locale' => 'Vùng',
    'Middlename' => 'Tên đệm',
    'Name' => 'Tên',
    'Order' => 'Thứ tự',
    'Page View' => 'Xem trang',
    'Parent Category' => 'Danh mục cha',
    'Path' => 'Đường dẫn',
    'Picture' => 'Ảnh',
    'Published' => 'Đã xuất bản',
    'Published At' => 'Xuất bản lúc',
    'Size' => 'Kích cớ',
    'Slug' => 'Bí danh',
    'Status' => 'Trạng thái',
    'Thumbnail' => 'Ảnh thumbnail',
    'Title' => 'Tiêu đề',
    'Type' => 'Loại',
    'Updated At' => 'Cập nhật lúc',
    'Updated at' => 'Cập nhật lúc',
    'Updater' => 'Người cập nhật',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Mã thành viên',
    'Username' => 'Tên đăng nhập',
    'Value' => 'Giá trị',
    'Short Description' => 'Mô tả ngắn',
    'Image list' => 'Danh sách ảnh',
    'Album' => 'Album ảnh',
    'Create album' => 'Tạo mới album ảnh',
    'Images in album' => 'Ảnh trong album',
    'Add new image for album' => 'Thêm ảnh mới cho album',
    'Description' => 'Miêu tả',
    'Partner name'  =>  'Tên đối tác',
    'Sort order'  =>  'Thứ tự hiển thị',
    'address'     =>    'Địa chỉ',
    'Product images'    =>  'Ảnh sản phẩm',
    'Product name'    =>  'Tên sản phẩm',
    'Intro-Uses'    =>  'Giới thiệu/công dụng',
    'Spec'          =>  'Thông số kỹ thuật',
    'Docs License'  =>  'Tài liệu và giấy phép liên quan',
    'M1 index'      =>  'Chỉ số M1',
    'Supplier'      =>  'Sản xuất',
    'Country'      =>  'Xuất sứ',
    'Safe Files'    =>  'TDS (nếu có)',
    'Spec File'     =>  'MSDS (nếu có)',
    'Product images max 5'   =>  'Ảnh sản phẩm ( tối đa 5 ảnh )',
    'In of stock'      =>  'Còn hàng',
    'Product code'      =>  'Mã hạt',
    'Material safety data'  =>  'Thông số an toàn vật liệu',
    'Application'  =>  'Ứng dụng',
    'Search'        =>  'Tìm kiếm',
    'Clear'         =>  'Xóa thông tin',
    'Add new image for product' =>  'Thêm ảnh sản phẩm',
    'Name in English'   =>  'Tên Tiếng Anh'
];
